apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: server #needs to match the app name on the connecting deployment/app
  ports:
    - port: 5000
      targetPort: 5000
